version: "3.9"  # optional since v1.27.0

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - "8000:8000"
    volumes: 
      - .:/usr/src/app
    depends_on: 
      - pgdb
  
  pgdb:
    image: postgres
    container_name: pgdb
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data/

volumes: 
  pgdata:
